#!/bin/bash

#############
# Shell env #
#############
# Export scripts path (from syscripts to dotfiles/bin)
#export PATH=$PATH:/${DOTFILES_FOLDER}/bin
export PATH=$PATH:${HOME}/syscripts

################
# Homebrew env #
################
# If on arm, add /opt path
if [ "$APPLE_ARCH" = "arm64" ]; then
	export PATH="/opt/homebrew/bin:${PATH}"
fi
# Disable auto-update and auto-cleanup
#export HOMEBREW_NO_AUTO_UPDATE=1;
# Run brew update once per day
export HOMEBREW_AUTO_UPDATE_SECS=86400
export HOMEBREW_NO_INSTALL_CLEANUP=1;
# Set cache age to 1 week
export HOMEBREW_CLEANUP_MAX_AGE_DAYS=7;
